In [1]:
import pandas as pd
import numpy as np

In [4]:
file = 'covid_vaccine_statewise.csv'

In [5]:
df = pd.read_csv(file)
df

,STATE,FIRST_DOSE_ADMINISTERED,SECOND_DOSE_ADMINISTERED,ONLY_FIRST_DOSE
0,Maharashtra,634056063,106939743,527116320
1,Rajasthan,540692573,98265014,442427559
2,Uttar Pradesh,521685072,113510032,408175040
3,Gujarat,508700924,107957315,400743609
4,West Bengal,445383722,97171961,348211761
5,Karnataka,375603538,67077829,308525709
6,Madhya Pradesh,342799240,55468394,287330846
7,Kerala,296140652,56636504,239504148
8,Bihar,282983123,51987462,230995661
9,Andhra Pradesh,240298705,59329289,180969416
10,Odisha,236771496,44938573,191832923
11,Tamil Nadu,233728503,48070438,185658065
12,Chhattisgarh,227246570,34886089,192360481
13,Telangana,162436602,31153530,131283072
14,Haryana,152764104,24145761,128618343
15,Jharkhand,133541375,23796126,109745249
16,Delhi,129954595,31182787,98771808
17,Punjab,123868427,17685245,106183182
18,Assam,95785669,22137176,73648493
19,Jammu and Kashmir,88524331,16658664,71865667
20,Uttarakhand,77224514,18652904,58571610
21,Himachal Pradesh,65440448,11659571,53780877
22,Tripura,46210363,12657361,33553002
23,Goa,12405212,2920004,9485208
24,Meghalaya,10439566,2859785,7579781
25,Manipur,9945111,2909426,7035685
26,Arunachal Pradesh,8834355,2602783,6231572
27,Mizoram,8670765,1972268,6698497
28,Chandigarh,7762642,1932170,5830472
29,Sikkim,7636937,1722327,5914610
30,Puducherry,7582196,1161991,6420205
31,Nagaland,7359529,2032141,5327388
32,Ladakh,4224179,1115592,3108587
33,Andaman and Nicobar Islands,3604186,530531,3073655
34,Dadra and Nagar Haveli and Daman and Diu,2011518,347413,1664105
35,Lakshadweep,824379,202227,622152

In [10]:
sorted(df['STATE'].unique())

['Andaman and Nicobar Islands',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chhattisgarh',
 'Dadra and Nagar Haveli and Daman and Diu',
 'Delhi',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu and Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Ladakh',
 'Lakshadweep',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Odisha',
 'Puducherry',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Telangana',
 'Tripura',
 'Uttar Pradesh',
 'Uttarakhand',
 'West Bengal']